[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[form]
  # Enable Netlify Forms
  [form.settings]
    # Redirect to success page after form submission
    action = "/success"